# holy fuck i hate regex

import re

# match digits and quantifiers
re_d = re.compile(r'((\d)\2*)')

def replace(match_obj):
    num = match_obj.group(1)
    return str(len(num)) + num[0] # replaces matches with 
    # the string generated by the instructions

def justrunalready(num, iter):
    for i in range(iter):
        num = re_d.sub(replace, num) # replace that shit
    print(len(num)) # prints the length of our final string
  
if __name__ == "__main__":
    num = '3113322113'
    partone = 40
    justrunalready(num, partone) # part one
    parttwo = 50
    justrunalready(num, parttwo) # part two
